### ISSUE TITLE
fabric8/jenkins-docker will change JAVA_HOME and hide jdk?

### ISSUE THREAD

**Issue by blindpirate** [fabric8io/jenkins-docker#88]
I was using `fabric8/jenkins-docker:2.2.288` and found `tools.jar` missing in jenkins's job running. So I checked `fabric8/jenkins-docker` image and its base image as follows:

![image](https://cloud.githubusercontent.com/assets/12689835/19962383/4b146744-a1f2-11e6-982a-286e3227cce5.png)

It seems that in `jenkins:2.19.1-alpine` jdk is installed properly but in `fabric8/jenkins-docker:2.2.288` jdk is missing - only jre is still there. I'm not sure if it's because of `RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt`.

Now my jenkins job will fail because of missing `tools.jar`. Any help?

Thank you very much.

**Comment by rawlingsj** [comment]
We're the QA'ing the release at the moment that includes the new Jenkins2 alpine base image (and the new lovely blue ocean UI).  Hopefully it will be released shortly.  Until then if you want to try the version that will be released you can find the yaml http://central.maven.org/maven2/io/fabric8/devops/apps/jenkins/2.2.294/

Using the correct openshift / kubernetes yaml for your target platform you can:
```
kubectl delete deployment jenkins
kubectl apply -f http://central.maven.org/maven2/io/fabric8/devops/apps/jenkins/2.2.294/jenkins-2.2.294-kubernetes.yml
```

That should run the new jenkins.

**Comment by blindpirate** [comment]
@rawlingsj Oh, thank you for your information, but I have modified some configurations to make `fabric8/jenkins-docker:2.2.288` fit in our usage. Could you please tell me why this occurs and how can I make of jdk on `fabric8/jenkins-docker:2.2.288`?

**Comment by rawlingsj** [comment]
The `fabric8/jenkins-docker:2.2.288` is using a different base image which by the looks of things doesn't include the jdk.  

I'd try and avoid too much customisation as that makes its very hard to upgrade when we do releases.  However, currently jenkins config is not persisted by a kubernetes volume as we hit problems with overwriting xml files that the docker image contains.

We need to find a way to persist jenkins customisations then you should be able to upgrade with our releases without loosing anything.  However we're not there yet.

I'm not sure what is failing in your setup but the idea is that we add build tools like a JDK to docker image that is used to build our applications.  Like this https://github.com/fabric8io/jenkins-pipeline-library/blob/master/workflows/maven/CanaryReleaseAndStage/Jenkinsfile#L33

So you could use that maven build image or create your own that includes the jdk you require?

FWIW this approach is being improved with the release that's waiting to go out as we use the multi container feature that @iocanel has contributed to https://github.com/jenkinsci/kubernetes-plugin

**Comment by blindpirate** [comment]
Thanks a lot!

Well, actually what I need is npm. Considering the wide usage of nodejs, I suggest to install nodejs into jenkins. Can I create a PR to do this?

**Comment by rawlingsj** [comment]
We would want to avoid installing any build tools into jenkins in favour of using one of these build pods describe above instead.  You could create your own npm build image as we've done with the maven and use it in the same way.  Then you'd just call `npm install` for example.

However a simpler approach that we use ourselves and in our node quickstarts is to use a docker onbuild image.  

I.e. you create a Dockerfile with the a node onbuild image https://hub.docker.com/_/node/
this contains the npm build tools
then outside the pipeline working locally you can docker build the image
or in Jenkins use [the existing fabric8 nodejs pipeline jenkinsfile](https://github.com/fabric8io/fabric8-jenkinsfile-library/blob/master/node/CanaryReleaseStage/Jenkinsfile#L14) 

```
echo 'FROM node:7-onbuild' > Dockerfile
docker build -t test/my-node-app .
docker run test/my-node-app
```

Or for when using fabric8 and Jenkins:

Add this jenkinsfile to your project (note we're updating this to use a deployment / deploymentconfig rather than replicationcontroller):
```
wget https://raw.githubusercontent.com/fabric8io/fabric8-jenkinsfile-library/master/node/CanaryReleaseStage/Jenkinsfile 
```

**Comment by blindpirate** [comment]
Okay, I will do that!

**Comment by blindpirate** [comment]
@rawlingsj BTW, I have read the scripts, what puzzle me most was - when and how was variable `kubernetes`  injected into the scripts? And which type is it? Tell me please.
